export const ImageConstant = {
  // Onboarding & Auth
  girl: require('../../assets/Images/girl.png'),
  image1: require('../../assets/Images/chose1.png'),
  image2: require('../../assets/Images/chose2.png'),
  welcome: require('../../assets/Images/Welcome.png'),
  zyaraApp: require('../../assets/Images/ZyaraApp.png'),
  BackArrow: require('../../assets/Images/back.png'),
  zyara: require('../../assets/Images/Zyara.png'),
  
  // Home Screen Icons
  Location: require('../../assets/Images/Location.png'),
  notification: require('../../assets/Images/notification.png'),
  search: require('../../assets/Images/search.png'),
  filter: require('../../assets/Images/filter.png'),
  // lines: require('../../assets/Images/lines.png'),

  // Calendar: require('../../assets/Images/calendar.png'),
  // user: require('../../assets/Images/user.png'),
  clock: require('../../assets/Images/clock.png'),
  upload: require('../../assets/Images/upload.png'),
  cammra: require('../../assets/Images/Group2.png'),
  // Additional Images
  buket: require('../../assets/Images/buket.png'),
  user1: require('../../assets/Images/user1.png'),
  user2: require('../../assets/Images/user2.png'),
  user3: require('../../assets/Images/user3.png'),
  user4: require('../../assets/Images/user4.png'),
  user5: require('../../assets/Images/user5.png'),
  user: require('../../assets/Images/user.png'),
  help: require('../../assets/Images/help.png'),
  setting: require('../../assets/Images/setting.png'),
  location2: require('../../assets/Images/location2.png'),
  nextarrow: require('../../assets/Images/next.png'),
  heart: require('../../assets/Images/heart.png'),
  booking: require('../../assets/Images/booking.png'),
  pay: require('../../assets/Images/pay.png'),
  logout :require('../../assets/Images/logout.png'),
  account: require('../../assets/Images/account.png'),
  home2 :require('../../assets/Images/home2.png'),
  Calander :require('../../assets/Images/calander.png'),
  chat :require('../../assets/Images/chat.png'),
  edit:require('../../assets/Images/edit.png'),
  editcammra:require('../../assets/Images/editcammra.png'),
  Categories:require('../../assets/Images/Categories.png'),
  No : require('../../assets/Images/No.png'),
  homePay : require('../../assets/Images/homePay.png'),
};